name: Publish Website

on:
  push:

  pull_request:
    types: [closed]

jobs:
  Deploy-Api-Dev:
    name: 🚀 Deploy Website
    runs-on: ubuntu-latest
    steps:
      - name: 🚚 Get latest code
        uses: actions/checkout@v2.1.0

      - name: Cache  💾
        uses: actions/cache@v2
        with:
          path: ${{ github.workspace }}/.next/cache
          key: ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-${{ hashFiles('**.[jt]sx?') }}
          restore-keys: |
            ${{ runner.os }}-nextjs-${{ hashFiles('**/package-lock.json') }}-

      - name: Install Node.js
        uses: actions/setup-node@v1
        with:
          node-version: 14.x

      - name: Install NPM packages
        run: npm install

      - name: Build project
        run: npm run export

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: access769798550.webspace-data.io
          FTP_USERNAME: ${{ secrets.FTP_USERNAME }}
          FTP_PASSWORD: ${{ secrets.FTP_PASSWORD }}
          METHOD: sftp
          LOCAL_DIR: out
          REMOTE_DIR: dev
          ARGS: --delete
